# Generated by Django 4.2.5 on 2023-12-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='titile',
            new_name='title',
        ),
    ]
