# Generated by Django 4.2.5 on 2023-10-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customer_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('are_you_an_old_user', models.BooleanField(default=True)),
            ],
        ),
    ]
