# Generated by Django 4.2.5 on 2023-10-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esm', models.CharField(max_length=100)),
                ('famil', models.CharField(max_length=100)),
                ('time_log', models.TimeField(help_text='enter the exact time!')),
            ],
        ),
    ]
