# Generated by Django 4.2.7 on 2023-11-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(to='blog.category', verbose_name='دسته بندی'),
        ),
    ]
