# Generated by Django 4.2.7 on 2023-11-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_category_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteringModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(max_length=80, verbose_name='نام خانوادگی')),
                ('birth_date', models.DateField(auto_now=True)),
                ('phone_number', models.IntegerField(max_length=12, verbose_name='شماره تلفن همراه')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
