# Generated by Django 4.2.7 on 2023-11-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_registeringmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeringmodel',
            name='phone_number',
            field=models.IntegerField(verbose_name='شماره تلفن همراه'),
        ),
    ]
