# Generated by Django 4.2.5 on 2023-10-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studiocoaches',
            old_name='income_per_hour',
            new_name='income_per_hours',
        ),
    ]
