# Generated by Django 4.2.5 on 2023-10-15 10:22
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_rename_income_per_hour_studiocoaches_income_per_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiocoaches',
            name='tarikhtavalod',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
