# Generated by Django 4.2.5 on 2023-09-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studiocoaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esm', models.CharField(max_length=20)),
                ('famil', models.CharField(max_length=50)),
                ('income_per_hour', models.CharField(max_length=10)),
            ],
        ),
    ]
